#
 # Wireless AP Nagios Host Definitions
 # Generated by: Sebastian Djurovic
 # Date: 2025-03-01 20:17
 # Version: v1.0
 #
 
 function ip(s){
     if (match(s, /([0-9]{1,3}\.){3}[0-9]{1,3}/)) return substr(s, RSTART, RLENGTH); 
     return ""
 }
 
 function safe(s){
     gsub(/[^A-Za-z0-9._-]/, "_", s); 
     return s 
 }
 
 function hostblock(h,ip){
 # Please refer to this reference https://www.tutorialspoint.com/nagios/nagios_hosts_and_services.htm as it may require adjustment depending on your own situation. 
 # I like to keep my host block and Service block together.
     print "define host {";
     print " use                     generic-switch";
     print " host_name               " h;
     print " alias                   " h;
     print " address                 " ip;
     print " hostgroups              wireless-aps";
     print "}\n";
     
     print "define services {";
     print " host_name               " h;
     print " Service_description PING";
     print " check_command_ping!100.0!,20%!500.0,60%";
     print " max_check_attempts      2";
     print " check_interval          2";
     print " retry_interval          2";
     print " check_period            24x7";
     print " check_freshness         1";
     print " contact_groups          admins";
     print "}\n";
 }
 
 # Below I've specified the start of the entry with AP. If you're using a different naming convention I recommend changing this. 
 /^AP[0-9]+/ {
     ipaddr = ip($0); if (!ipaddr) next;
     h= safe($1);
    
     # I've had issue bellow, if you've got a variety of naming conventions please change this as well. You can comment out the following 5 lines.
     # Replace those lines with 'h = $1'
     if ((h) in seen) {
         split(ipaddr, o, ".");
         h = h "_" o[4];
     }
     seen(h)=1;
     hostblock(h,ipaddr);
 }
 AWK
